/**
 * @file eez_home_screen_view.h
 * @brief EEZ-backed implementation of IHomeScreenView_t.
 *
 * Wraps objects.home_time and objects.home_line1 generated by EEZ Studio.
 * All lv_*() calls are guarded with lv_lock()/lv_unlock() — safe to call
 * from any thread (e.g. Control AO).
 *
 * @note This header MAY be included anywhere; lvgl.h is kept in the .c file
 *       so Presenters remain LVGL-free.
 */
#ifndef EEZ_HOME_SCREEN_VIEW_H
#define EEZ_HOME_SCREEN_VIEW_H

#include "presentation/interfaces/i_home_screen_view.h"

#ifdef __cplusplus
extern "C"
{
#endif

    /**
     * @brief Get the singleton EEZ-backed view.
     *
     * @note Not thread-safe to call before ui_init() has returned.
     * @return Pointer to the static IHomeScreenView_t backed by EEZ objects.
     */
    IHomeScreenView_t *EezHomeScreenView_GetInterface(void);

#ifdef __cplusplus
}
#endif

#endif /* EEZ_HOME_SCREEN_VIEW_H */
